# Generated by Django 4.0.6 on 2022-08-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_quantity_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
