# Generated by Django 4.0.6 on 2022-08-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_role_remove_user_is_admin_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(0, 'none'), (1, 'customer'), (2, 'restaurant')], primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.role'),
        ),
    ]
